spring:
  datasource:
    url: jdbc:mysql://localhost:3306/backdabang?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver